SrodkiTrwale/Models/FixedAssets.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SrodkiTrwale.Models
{
    public class FixedAssets
    {
        [Key]
        public int ID { get; set; }

        [ForeignKey("Categories")]
        public int CategoriesID { get; set; }

        [ForeignKey("Users")]
        public int UserID { get; set; }

        public string ImageUrl { get; set; }
        public decimal AmortizationValue { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal CurrentPrice { get; set; }

        [Required]
        [MaxLength(20, ErrorMessage = "Nazwa jest za długa")]
        public string Name { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateTime DateOfCollections { get; set; }

        public virtual Users Users { get; set; }
        public virtual Categories Categories { get; set; }
    }
}

SrodkiTrwale/Models/ViewModel/QuantityOfAssets.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SrodkiTrwale.Models.ViewModel
{
    public class QuantityOfAssets
    {
        public int Quantity { get; set; }
        public string Name { get; set; }
    }
}

SrodkiTrwale/Controllers/FixedAssetsController.cs
using Newtonsoft.Json;
using PagedList;
using RestSharp;
using SrodkiTrwale.Context;
using SrodkiTrwale.Models;
using SrodkiTrwale.Models.ApiModels;
using SrodkiTrwale.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SrodkiTrwale.Controllers
{
    [Authorize]
    public class FixedAssetsController : Controller
    {
        private SrodkiContext db = new SrodkiContext();

        public FixedAssetsController()
        {

        }
        // GET: FixedAssets
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Date" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var fixedAssets = db.FixedAssets.Include(f => f.Categories).Include(f => f.Users);
            if (!String.IsNullOrEmpty(searchString))
            {
                fixedAssets = fixedAssets.Where(s => s.Name.Contains(searchString)
                                       || s.Users.FirstName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    fixedAssets = fixedAssets.OrderByDescending(s => s.Name);
                    break;

                case "Date":
                    fixedAssets = fixedAssets.OrderBy(s => s.DateOfCollections);
                    break;

                case "date_desc":
                    fixedAssets = fixedAssets.OrderByDescending(s => s.DateOfCollections);
                    break;

                default:
                    fixedAssets = fixedAssets.OrderBy(s => s.Name);
                    break;
            }
            //ilosc rekordow na strone
            int pageSize = 2;
            int pageNumber = (page ?? 1);
            return View(fixedAssets.ToPagedList(pageNumber, pageSize));
        }

        // GET: FixedAssets/Details/5
        public ActionResult Details(int? id)
        {
            var amortizationFromDb = db.Amortization.Include(x => x.AmortizationRows).ToList();
            List<SelectListItem> listOfAmortization = new List<SelectListItem>();
            foreach (var item in amortizationFromDb)
            {

                listOfAmortization.Add(new SelectListItem { Text = item.AmortizationValue.ToString(), Value = item.AmortizationValue.ToString() });
            }

            var asset = db.FixedAssets.FirstOrDefault(x => x.ID == id);
            if (asset != null && !(asset.ImageUrl == null || asset.ImageUrl == ""))
            {
                FixedAssetDetailsModelView modelview1 = new FixedAssetDetailsModelView
                {
                    Categories = asset.Categories.CatTypes,
                    DateOfCollections = asset.DateOfCollections,
                    Name = asset.Name,
                    UserName = asset.Users.LastName,
                    ImageUrl = asset.ImageUrl,
                    ID = asset.ID,
                    CurrentPrice = asset.CurrentPrice,
                    ListOfAmortization = listOfAmortization

                };
                ViewBag.ImageUrl = asset.ImageUrl;
                return View(modelview1);
            }
            FixedAssetDetailsModelView modelview = new FixedAssetDetailsModelView
            {
                Categories = asset.Categories.CatTypes,
                DateOfCollections = asset.DateOfCollections,
                Name = asset.Name,
                UserName = asset.Users.LastName,
                ImageUrl = "~/Obrazki/brak.png",
                ID = asset.ID,
                CurrentPrice = asset.CurrentPrice,
                ListOfAmortization = listOfAmortization
            };
            ViewBag.ImageUrl = "~/Obrazki/brak.png";
            return View(modelview);
        }

        // GET: FixedAssets/Create
        public ActionResult Create()
        {
            ViewBag.CategoriesID = new SelectList(db.Categories, "ID", "CatTypes");
            ViewBag.UserID = new SelectList(db.Users, "ID", "FirstName");
            return View();
        }

        // POST: FixedAssets/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FixedAssetCreateModelView model)
        {
            if (ModelState.IsValid)
            {
                var asset = new FixedAssets
                {
                    CategoriesID = model.CategoriesID,
                    DateOfCollections = DateTime.Now,
                    Name = model.Name,
                    UserID = model.UserID,
                    AmortizationValue = model.AmortizationValue,
                    PurchasePrice = model.PurchasePrice,
                    CurrentPrice = model.PurchasePrice

                };

                if (model?.ImageFile?.FileName != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                    string extension = Path.GetExtension(model.ImageFile.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    string path = "~/Obrazki/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Obrazki/"), fileName);
                    model.ImageFile.SaveAs(fileName);
                    asset.ImageUrl = path;
                }

               
                
                db.FixedAssets.Add(asset);
                db.SaveChanges();
                return RedirectToAction("Index");
            };

            ViewBag.CategoriesID = new SelectList(db.Categories, "ID", "CatTypes", model.CategoriesID);
            ViewBag.UserID = new SelectList(db.Users, "ID", "FirstName", model.UserID);
            return View(model);
        }

        public async Task<ActionResult> Amortize(FixedAssets fixedAsset)
        {
            var fixedAssetFromDb = await db.FixedAssets.FirstOrDefaultAsync(x => x.ID == fixedAsset.ID);
            fixedAssetFromDb.CurrentPrice = fixedAssetFromDb.CurrentPrice - (fixedAssetFromDb.CurrentPrice * fixedAsset.AmortizationValue / 100);

            db.Entry(fixedAssetFromDb).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Details/" + fixedAsset.ID);
        }

        // GET: FixedAssets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FixedAssets fixedAssets = db.FixedAssets.Find(id);
            if (fixedAssets == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoriesID = new SelectList(db.Categories, "ID", "CatTypes", fixedAssets.CategoriesID);
            ViewBag.UserID = new SelectList(db.Users, "ID", "FirstName", fixedAssets.UserID);
            return View(fixedAssets);
        }

        // POST: FixedAssets/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CategoriesID,UserID,Name,DateOfCollections")] FixedAssets fixedAssets)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fixedAssets).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoriesID = new SelectList(db.Categories, "ID", "CatTypes", fixedAssets.CategoriesID);
            ViewBag.UserID = new SelectList(db.Users, "ID", "FirstName", fixedAssets.UserID);
            return View(fixedAssets);
        }

        // GET: FixedAssets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FixedAssets fixedAssets = db.FixedAssets.Find(id);
            if (fixedAssets == null)
            {
                return HttpNotFound();
            }
            return View(fixedAssets);
        }

        // POST: FixedAssets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FixedAssets fixedAssets = db.FixedAssets.Find(id);
            db.FixedAssets.Remove(fixedAssets);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult QuantityOfAssets()
        {
            var quantity = new QuantityOfAssets();
            quantity.Name = "Ilosc wszystkich: ";
            quantity.Quantity = db.FixedAssets.Count();

            return View(quantity);
        }
        public ActionResult AmortizeFixedAsset(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FixedAssets fixedAsset = db.FixedAssets.Find(id);
            if (fixedAsset == null)
            {

SrodkiTrwale/Views/FixedAssets/Create.cshtml
@model SrodkiTrwale.Models.ViewModel.FixedAssetCreateModelView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "FixedAssets", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>FixedAssets</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageFile" />
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Categories", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoriesID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoriesID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("User", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PurchasePrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PurchasePrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PurchasePrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AmortizationValue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AmortizationValue, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AmortizationValue, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SrodkiTrwale/Views/FixedAssets/Delete.cshtml
@model SrodkiTrwale.Models.FixedAssets

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FixedAssets</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categories.CatTypes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categories.CatTypes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Users.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Users.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfCollections)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfCollections)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SrodkiTrwale/Views/FixedAssets/Details.cshtml
@model SrodkiTrwale.Models.ViewModel.FixedAssetDetailsModelView

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<br />
<div>
    @using (Html.BeginForm("Amortize", "FixedAssets"))
    {
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Picture")
            </dt>
            <dd>
                <img src="@Url.Content(@ViewBag.ImageUrl)" alt="Image" style="height: 100px; width: 75px" />
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Categories)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Categories)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateOfCollections)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateOfCollections)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ListOfAmortization)
            </dt>

            <dd>
                @Html.HiddenFor(model => model.ID)
                @Html.DropDownListFor(model => model.AmortizationValue, Model.ListOfAmortization, "Wybierz wartość amortyzacji")
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CurrentPrice)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CurrentPrice)
            </dd>

        </dl>
        <input type="submit" value="Amortize!" />
    }
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
    @*@Html.ActionLink("Amortize!", "Amortize", new { value = Model.AmortizationValue, fixedAssetsId = Model.ID })
    @Html.ActionLink("Amortize!", "Amortize", new { amortizationValue = Model.AmortizationValue, fixedAssetsId = Model.ID })*@
</p>

SrodkiTrwale/Views/FixedAssets/Edit.cshtml
@model SrodkiTrwale.Models.FixedAssets

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FixedAssets</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.Label("Categories", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoriesID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoriesID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("User", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfCollections, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfCollections, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfCollections, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SrodkiTrwale/Views/FixedAssets/GenerateReportForAssets.cshtml
@model IEnumerable<SrodkiTrwale.Models.ApiModels.FixedAssetApiModel>

@{
    ViewBag.Title = "GenerateReportForAssets";
}

<h2>GenerateReportForAssets</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.categoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.dateOfCollections)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.categoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dateOfCollections)
        </td>
    </tr>
}

</table>

SrodkiTrwale/Views/FixedAssets/Index.cshtml
@model PagedList.IPagedList<SrodkiTrwale.Models.FixedAssets>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Quantity", "QuantityOfAssets")
</p>

@using (Html.BeginForm("Index", "FixedAssets", FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>

        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
         
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfCollections)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID }) 
                @*@Html.ActionLink("Amortize", "AmortizeFixedAsset", new { id = item.ID })*@
                
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

SrodkiTrwale/Views/FixedAssets/QuantityOfAssets.cshtml
@model SrodkiTrwale.Models.ViewModel.QuantityOfAssets
@{
    ViewBag.Title = "QuantityOfAssets";
}

<h2>QuantityOfAssets</h2>

<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayFor(model => model.Name)
        </dt>

   

      

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        

    </dl>
</div>